{% set name = "QuantLib" %}
{% set version = "1.41" %}
{% set sha256 = "c5e9a30fce129660932e643647eb9a14e19ec24344d6b813c57c054187b03bdd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lballabio/QuantLib/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # test-suite build defines BOOST_ALL_DYN_LINK when Boost_USE_STATIC_LIBS=OFF,
    # which forces auto-linking against versioned boost shared libs that don't
    # exist under that name in libboost-devel. We only need the header-only parts.
    - patches/0001-Remove-use-of-BOOST_ALL_DYN_LINK.patch  # [win]

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('quantlib', max_pin='x') }}  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - cmake
    - make  # [unix]
    - ninja-base  # [win]
  host:
    # libboost-devel has run_exports that auto-pin libboost on the downstream,
    # so we don't need to list libboost in `run:` explicitly.
    - libboost-devel

test:
  commands:
    - quantlib-test-suite --log_level=message  # [win]
    # quantlib-config is built only for unix-like systems
    - quantlib-config --version  # [not win]

about:
  home: https://www.quantlib.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The QuantLib C++ library
  description: The QuantLib project is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  recipe-maintainers:
    - timkpaine
