{% set name = "QuantLib" %}
{% set version = "1.27" %}
{% set sha256 = "5c2cab0f9bbcdcd3ca1b45d7930b3ab7e120857587b6f61c463b2a012a8bc6a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lballabio/QuantLib/releases/download/{{ name }}-v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('quantlib', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - cmake
    - make  # [unix]
  host:
    - boost-cpp
  run:
    - boost-cpp

test:
  commands:
    - cd build && ./test-suite/quantlib-test-suite --log_level=message  # [unix]

about:
  home: https://github.com/lballabio/QuantLib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The QuantLib C++ library
  description: The QuantLib project (https://www.quantlib.org) is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  recipe-maintainers:
    - timkpaine
