# this package is not intended to go on the default channel
{% set name = "QuantLib" %}
{% set version = "1.29" %}
{% set sha256 = "b8127fb6fe5562dfabfcb7d62df4ba2f018de39d7fbe7df2b7a688578516b4b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/lballabio/QuantLib/releases/download/{{ name }}-v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('quantlib', max_pin='x') }}  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - cmake
    - make  # [unix]
    - ninja-base  # [win]
  host:
    - boost-cpp 1.73.0
  run:
    - boost-cpp >=1.73.0,<2.0a0

test:
  commands:
    - quantlib-test-suite --log_level=message  # [win]
    # quantlib-config is built only for unix-like systems
    - quantlib-config --version  # [not win]

about:
  home: https://www.quantlib.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: The QuantLib C++ library
  description: The QuantLib project is aimed at providing a comprehensive software framework for quantitative finance. QuantLib is a free/open-source library for modeling, trading, and risk management in real-life.
  doc_url: https://www.quantlib.org
  dev_url: https://github.com/lballabio/QuantLib

extra:
  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/38602
    reason: "needed by Reinsurance Group"
    recipe-maintainers:
      - ianaobi
      - timkpaine
